spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/planillas?currentSchema=mutant-detector
    username: proteccion
    password: proteccion
    driver-class-name: org.postgresql.Driver
    platform: postgres
  flyway:
    enabled: false
  jpa:
    database: POSTGRESQL
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 20
          lob:
            non_contextual_creation: true
          cache:
            use_query_cache: false
            use_second_level_cache: false
            use_structured_entries: false
            use_minimal_puts: false
        temp:
          use_jdbc_metadata_defaults: false