server:
  error:
    include-message: always

spring:
  datasource:
    #url: jdbc:postgresql://localhost:5432/planillas?currentSchema=mutant-detector
    #url: jdbc:postgresql://snappy-catcher-311002:us-east1:mutant-detector
    username: postgres
    password: mutant
    driver-class-name: org.postgresql.Driver
    platform: postgres
    continue-on-error: true
    initialization-mode: always
  cloud:
    gcp:
      sql:
        database-name: postgres
        instance-connection-name: snappy-catcher-311002:us-east1:mutant-detector

  flyway:
    enabled: true
  jpa:
    database: POSTGRESQL
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 20
          lob:
            non_contextual_creation: true
          cache:
            use_query_cache: false
            use_second_level_cache: false
            use_structured_entries: false
            use_minimal_puts: false
        temp:
          use_jdbc_metadata_defaults: false